### ISSUE TITLE
OCT 4, 2014 — Postmortem Report

### ISSUE THREAD

**Issue by affinity-matrix** [dancejs/Oakland#1]
**SUCCESS**

_I think we can all agree that the first RaveJS was a successful endeavor!_
_Huge thanks to the legendary @bcoe for taking the initiative to get this ball rolling!_
_And of course, the illustrious @mikeal for making this whole thing possible in the first place._

**Let's take some time to harness the momentum we have, and do a little continual improvement:**

Now that the _first ever_ DanceJS has come and gone, let's discuss what was awesome, what was not so awesome, and what we'd like to do differently for future events. Input on the actual process of registering and acting on feedback also welcome!

**Comment by affinity-matrix** [comment]
We suffered our fair share of technical difficulties, which I think would be valuable to enumerate.

It's also worth noting that opening the space up (removing the rolling panels) seemed to help, and noise only seemed to be a problem when the #robotdanceparty made its way outside. 

I also had a lot of people express their disappointment in missing the talks, so I wondering if we could experiment with having the talks to take place slightly later in the evening. Imagine a dance-presentation-dance sandwich.

One thought that occurred to me was the possibility of keeping music playing (lowered) from rear channel whilst the presenter is talking, with voice amplification over the front channel. I believe this would require a more sophisticated speaker setup, potentially even another mixer? @othiym23 may be able to elaborate!

**Comment by othiym23** [comment]
> One thought that occurred to me was the possibility of keeping music playing (lowered) from rear channel whilst the presenter is talking, with voice amplification over the front channel.

This would have been easy to do with the setup we had last night, because the rear PA had a completely independent mixer from the front one. However, that leads to a larger question: is Oakland DanceJS primarily about _hanging out_ or _getting down_? After the talks ended, it looked like about a 3:2 mixture of "people hanging out and talking" : "people on the dance floor" (not all of whom were dancing). One of the questions I have about scaling up the number of attendees is how to properly accommodate the dancers and the chatters. I estimate we could get about 250-300 serious partiers into that space (although I seem to recall that being close to the limit the fire marshal allows in the space), but that number drops a lot if most folks are there to chill and maybe dance a little. I don't have an opinion about which way things should go (I like both kinds of events), it's just something to think about.

Also, having music playing _during_ the talks sounds like it would be stressful for the speakers and distracting for viewers; it's really tough to do that in a balanced / unobtrusive way.

> I was wondering if we could experiment with having the talks to take place slightly later in the evening. Imagine a dance-presentation-dance sandwich.

I think that's a good idea. Maybe have somebody start up the night with space disco / kosmiche / pop / electro-house type stuff, and somebody bring the drops for the second set. Also I gotta find a place for this dolphincore / dadwave idea I have in my head. Anyway, yes, Rave Standard Time is that nobody shows up for anything much before 10, so having talks so early is doubly surprising. The talks were good, too, so pushing them later to get a larger audience really is a good idea.

OK, real postmortem time.

> We suffered our fair share of technical difficulties, which I think would be valuable to enumerate.
- PA was overdriven and conked out 5-10 times
- not enough amplification for the front speakers
- not enough power cords for all of the lights _and_ all the sound gear
- no stands for the lights
- poor variety of cabling
- no patch bay for sources and outputs
- no monitoring for speakers and DJs
- too little sound checking
- poor tools for tuning the PA for the room:
  - no compressor
  - no limiter
  - no parametric EQ
  - no tunable crossover
  - no delay b/w front and rear sound systems
- mixer was pretty limited
  - not enough RCA / 1/8" inputs
  - USB input wasn't very tunable
  - limited outputs: only 1 stereo XLR pair (front PA), 1 unbalanced 1/4" pair (rear PA), and one RCA tape monitor pair (dancing robot)
  - too accessible

That last point requires a little explanation. I unreservedly apologize to everyone for being such an unrepentant asshole about the mixer, but it's a real hazard to have the final mixdown steps tweaked once the event starts by anyone except the person responsible for the PA. As a former DJ myself, I can tell you that the sound system _never_ sounds loud or bumpin' enough to performers, especially when you're set up behind the speakers (as you should be if you're going to have mikes, to minimize opportunities for feedback).

It is the most natural thing in the world to push the volume levels up as you get more into your set, but the clipping indicators on the amp are no joke – once they start lighting up, you have about 2 minutes to bring back the sound levels _significantly_ before your amp is going to take a 3-5 minute nap to cool down. Keeping the amp cooler would have helped a little, but once the amp starts clipping, it's making heat faster than it can get rid of it, even if you have fans blowing directly on it, so the name of the game is keeping it from getting to that point.
- Putting a [compressor-limiter](http://www.behringer.com/EN/Products/MDX4600.aspx) in the signal chain allows you to safely limit the hotness of the signal going into the amplifiers, and since compression increases the perceived loudness of the music by squashing its dynamic range, it generally allows DJs to feel like they're pushing louder beats without conking out the sound system. It also helps create a more consistent dynamic range and more consistent perceived loudness, which was an issue at a few points last night.
- Having a [parametric equalizer](http://www.meyersound.com/products/processor_drive_systems/cp-10/) allows you to precisely control where the power from the amplifier is going – in particular, it keeps you from sinking all your current into super low frequencies (<50Hz) that can basically absorb all the power in the world without getting appreciably louder / thumpier, and it keeps you from blowing out your tweeters, which tend to be the most efficient components in the output chain, and also the most effective at shredding everyone's hearing.
- A [tunable crossover](http://www.ebay.com/itm/Furman-TX-324-2-Channel-Tunable-Crossover-Limiter-Vintage-Rack-/171144605220) (holy shit I'm pretty sure that's the exact model the Badlander Sound System had 20 years ago) plus a dedicated amplifier for each of the drivers (as a pair) and the subwoofer would allow us to make more efficient use of power.
- Although the space was small enough that this wasn't an issue, and because y'all whippersnappers use DJ tools like Live or Traktor you don't need to beatmatch as much, having the ability to tune the delay between the front and rear speakers can make a real difference to the clarity of the sound when you're running a double-sided / 4-corner sound system like we were last night. Not really an issue unless we start doing things in warehouses or large convention center rooms, but there was a perceptible delay between the front and back halves of the room last night.
- Given the diversity of things that people in the DanceJS crowd are going to want to use to make sounds, some kind of flexible patch bay that can take XLR, balanced and unbalanced 1/4", 1/8", RCA, and probably USB inputs and outputs would be extremely helpful. Also a mixer with a more flexible bus would be extremely useful – we made everything work out last night, but it was awkward at times, as @TheAlphaNerd and @nexxy can attest.

Some or all of those may be available as [integrated units](http://peavey.com/products/index.cfm/item/706/115825/VSX%26trade%3B26) now; it's been years since I looked at this stuff seriously. But the engineering principles they embody are important, and give you the flexibility to make the most of your gear and the space you're playing in – especially if you set them during sound check and then LEAVE THEM ALONE for the rest of the night. A sound guy I used to work with would basically hide all of the above from the DJs and wouldn't let anybody else touch them; most of San Francisco's nightclubs have dedicated sound engineers and several of them keep the post-mixer signal chain tuning gear in locked cabinets(!). Sorta wimpy sound is a better user experience than the PA just cutting out at unpredictable intervals.

Please note that I am _not_ criticizing anybody here; I think things went really well last night, and for all of the above, I checked the sound at several points in the evening and it sounded pretty much fantastic given the gear and room - clear and with a fairly flat (albeit low on the bass – hard to avoid with just the one subwoofer) frequency curve.

**Comment by bcoe** [comment]
First off I had a ton of fun, and was happy with how things went in general:

The good:
- I loved the venue, I've followed up with Christina hopefully they'd be open to future events.
- I loved the robot; it helped get people dancing, and was worth its weight in gold.
- @nexxy you did an awesome job with lighting, the mood was perfect.
- @othiym23 you were an amazing sound technician, thank you!

Needs improvement:
- it was hard to DJ with the bass cutting out, we definitely need some more equipment and a sound check that puts things under more stress.
- talks were great! But I agree too many people missed them. Let's lead with a chill DJ set before talks while people file in?
- it would be good to dial speakers and performers in sooner next time, it didn't help that one speaker backed out.
- same goes for sponsors, we broke even almost, thanks to the amazing work of @TheAlphaNerd getting rd.io on board,

Amazing work everyone, can't wait for the next one.

**Comment by NHQ** [comment]
I had a blast.

The format does not need to be linear if space permits otherwise. If we move our event to the OMNI or similar, we'll have all kinds of space: a main dance hall for assembly, and plenty of room to kick it (possible soul train?).  A cafe for collaboratives n jams.  Side spaces to demo...
