### ISSUE TITLE
Dance.js JSFest, Dec 13th

### ISSUE THREAD

**Issue by bcoe** [dancejs/Oakland#2]
Here we go again, @mikeal has asked us to throw our next Dance.js on December 13th at JSFest.
- I've already followed up with 25C and we can use the venue on the 13th.
- I've emailed the robot's entourage.
- @gsilk has expressed an interest in doing a talk that leads into a programmatic performance.
- @mikeal has been chatting with @othiym23, regarding what's needed to improve the sound system.
- Anita's Dropship would also be interested in doing a talk this time.

What if we have a short meeting sometime this weekend, to have a postmortem regarding our first event. And to start initial planning for JSFest?

**Comment by aulvi** [comment]
I cannot attend in person but if you wanna do a Hangout or something I can certainly jump in. Would love to help out wherever possible, gives me yet another reason to be in the bay in Dec.

**Comment by MylesBorins** [comment]
I also will be unable to make it this weekend, although I could join via hangout.

**Comment by othiym23** [comment]
Yeah, I have some commitments this weekend, although I could probably do Hangouts or Skype (also I've probably spent more words on postmortemy things than I should have anyway).

**Comment by bcoe** [comment]
I'm feeling sufficiently recovered from the last event, and my excitement levels are on the rise for December 13th. Can anyone sync-up this weekend, to start discussing the details of the next Dance.js -- for starters, I'd love to get the website fixed up.

**Comment by MylesBorins** [comment]
I'm having a House warming party at my place on Saturday if you want to use it as a meeting location

**Comment by bcoe** [comment]
Can anyone make it to Oakland.js tomorrow to do some initial planning for Dance.js JSFest?

**Comment by mikeal** [comment]
yes

**Comment by zeke** [comment]
I can't make it tonight, but I can help out for the Dec 13 edition of DanceJS if help is needed.

And I am now following the repos. :)

**Comment by MylesBorins** [comment]
I cannot make it myself either… please let me know how I can’t help though.

**Comment by NHQ** [comment]
what's news here?

i wanted to offer some goods for the event.  
- me and @substack have jammed together a la mode live code since several boogie barns ago. I am referring to the same kind of stuff he showed off at the inaugural dancejs. 
- I like to accompany electronic music with acoustic play, namely on my amazing 28" marching bass gong.
- my band / music project, consisting of several musicians, is a combo of electronic, acoustic, live code and pure javascript synths.  I don't know if dancejs is ready for us tho!
- i have over the past couple years written many basic audio DSP modules in JS, and use them to build synths.

Most of my music on soundcloud is in part, or in whole, javascript composed. Not to be confused with my "band" project, my soundcloud is, like all social services I use, is a repository of etudes. Even twitter.

**Comment by bcoe** [comment]
@NHQ I was talking to @substack a few Oakland.JS' ago, I would love to have an open-jam session as towards the end of the evening again ... 10:45 onwards? ... showing off synths and generative music, I know @gsilk is giving a talk on generating music in Emacs.

You should all sync up., I think anything goes for this portion of this evening, if we want to introduce a live component as well :100:
