### ISSUE TITLE
we need to buy some equipment for JSFest on Dec 13th

### ISSUE THREAD

**Issue by bcoe** [dancejs/Oakland#4]
CC: @TheAlphaNerd @nexxy @mikeal @gabrielsilk @linclark @aulvi 

The next JSFest is on December 13th at JSFest (I can't wait!, it's been long enough that I know I'm itching to dance, hangout with people, and  play some music).

We don't want the music cutting out like it did at the last Dance.js, so we've got to grab some equipment. @othiym23 suggests, as a minimum, that we should grab compressor/limiter and an amplifier comparable to what we had at the last event.

Does anyone have opinions about what we should grab (I was thinking we could perhaps hit up a Guitar Center next week to grab the equipment).

**Comment by mikeal** [comment]
Please use the format of "links to things on Amazon available through Prime" whenever possible :)

**Comment by bcoe** [comment]
Here's some equipment that I think would be worth grabbing, all Amazon Primeable:

## Compressor / Limiter

Both these options seemed great, and came highly reviewed. Most of our other equipment is Behringer, so it might be worth sticking with this theme:

http://www.amazon.com/Behringer-MDX2600-BEHRINGER-COMPOSER-PRO-XL/dp/B0002E4ZKU/ref=pd_sim_sbs_MI_4?ie=UTF8&refRID=02CD1254T8PQ5946ECX1

http://www.amazon.com/DBX-266xs-Comprssor-Gate/dp/B004NDFRVC/ref=pd_sim_sbs_MI_1?ie=UTF8&refRID=0KR6TKQDSC168M3GF4R8

## Amp

Rather than buying a more powerful amplifier, @othiym23 and I felt it would make more sense to power the subwoofer with a separate amp than the other speakers. Our subwoofer is 1600 watts, so I figured this 2000 watt amp would do the trick, and it matches our Behringer theme:

http://www.amazon.com/Behringer-EP2000-BEHRINGER-EUROPOWER/dp/B001W3BM24/ref=sr_1_2?ie=UTF8&qid=1416100235&sr=8-2&keywords=Behringer+Europower

## Rack

We're getting enough equipment now that it makes the DJ setup fairly messy, it would be nice to have a rack to place our units in:

http://www.amazon.com/SKB-DJ-Station-Roto-Mold-Reinforced/dp/B0002NQSB0/ref=sr_1_7?ie=UTF8&qid=1416100300&sr=8-7&keywords=DJ+rack+mount

http://www.amazon.com/StarTech-com-Mounting-Cabinet-Computer-CABSCREWS/dp/B00008VF98/ref=sr_1_3?s=musical-instruments&ie=UTF8&qid=1416100927&sr=1-3&keywords=rack+mounting+screws

It would also be nice to have a stand for our laptops:

http://www.amazon.com/PYLE-PRO-PLPTS25-Laptop-Computer-Stand/dp/B004HJ1ZB8/ref=sr_1_1?ie=UTF8&qid=1416100360&sr=8-1&keywords=DJ+stand

## Lighting

One or two lighting stands would be great:

http://www.amazon.com/Odyssey-LTP2-Tripod-Stand-T-Bar/dp/B0002DUWVM/ref=sr_1_8?s=musical-instruments&ie=UTF8&qid=1416101347&sr=1-8&keywords=lighting+stand

## Wires

We were somewhat limited as to where we could place the lighting, due to a lack of extension cords and computer cords, it would be worth grabbing a few.

http://www.amazon.com/Monoprice-109764-3-Feet-Stereo-Plated/dp/B00AJHB8R8/ref=sr_1_2?ie=UTF8&qid=1416100483&sr=8-2&keywords=stereo+cable

http://www.amazon.com/US-Wire-74025-25-Foot-Extension/dp/B002HWRS7W/ref=sr_1_2?ie=UTF8&qid=1416100631&sr=8-2&keywords=25%27+extension

http://www.amazon.com/Belkin-6-Feet-Replacement-Power-Cord/dp/B00000J1UQ/ref=sr_1_2?ie=UTF8&qid=1416100695&sr=8-2&keywords=pc+cord

Just a wish list to start a conversation going, what do you think @othiym23, @mikeal?

**Comment by othiym23** [comment]
It'd probably be cheaper to buy monoprice stuff directly from monoprice, but mikeal's the purser here, not me, so I'm fine with whatever he's fine with.

I would actually like to get paired amps – different amps have different output curves, and that makes getting the levels set right for both the speakers and the amps a little trickier. That's why I wanted to know what the existing amp is, so we could just get another one of those. It's not a huge deal.

What would help there would be getting an active crossover:

http://www.amazon.com/Behringer-CX2310-BEHRINGER-SUPER-X-PRO/dp/B0002Z82LM/ref=sr_1_2?ie=UTF8&qid=1416102208&sr=8-2&keywords=active+crossover

And I agree, having all this stuff in a rack-mount hard case, preferably with both casters and heavy-duty handles, would be ideal:

http://www.amazon.com/SKB-19-R1010-Gig-Rig/dp/B0002GL7SG/ref=sr_1_28?s=musical-instruments&ie=UTF8&qid=1416102346&sr=1-28&keywords=rack+mount+hard+case

Thanks for keeping this ball rolling, @bcoe!

**Comment by bcoe** [comment]
@othiym23 our other amp is a 4000 watt Behringer:

http://www.amazon.com/Behringer-EP4000-BEHRINGER-EUROPOWER/dp/B001U5JFNM/ref=sr_1_1?s=musical-instruments&ie=UTF8&qid=1416102671&sr=1-1&keywords=Behringer%3A+EUROPOWER+EP4000

It's more expensive, unfortunately, but this would ensure a pair.

**Comment by othiym23** [comment]
I didn't notice that your suggested amp was a Behringer of the same brand, so as you were (although a matched pair appeals to my more compulsive tendencies). A crossover would still be handy.

**Comment by mikeal** [comment]
As of December 20th I'll be leasing an full time event space in Oakland near the waterfront. We'll be able to start installing lighting, projection, sound and video recording equipment in December. I'll also be installing a nice coffee bar, of course :)

With that in mind I'd like to avoid purchasing additional lighting or transportable cases since we won't be transporting equipment as much in the future and the lighting we want to buy for permanent installation may be different than lighting we would use that is transportable.

Could we get a new final list of equipment to buy with that in mind :)

**Comment by MylesBorins** [comment]
This is one of the most exciting things I've heard in a while

**Comment by bcoe** [comment]
@mikeal that's very exciting, can't wait to build out the sound system in that space! Here's the modified list of equipment:

A compressor/limiter:

http://www.amazon.com/Behringer-MDX2600-BEHRINGER-COMPOSER-PRO-XL/dp/B0002E4ZKU/ref=pd_sim_sbs_MI_4?ie=UTF8&refRID=02CD1254T8PQ5946ECX1

An amplifier for the subwoofer:

http://www.amazon.com/Behringer-EP2000-BEHRINGER-EUROPOWER/dp/B001W3BM24/ref=sr_1_2?ie=UTF8&qid=1416100235&sr=8-2&keywords=Behringer+Europower

Some extra cables:

http://www.amazon.com/Monoprice-109764-3-Feet-Stereo-Plated/dp/B00AJHB8R8/ref=sr_1_2?ie=UTF8&qid=1416100483&sr=8-2&keywords=stereo+cable

http://www.amazon.com/US-Wire-74025-25-Foot-Extension/dp/B002HWRS7W/ref=sr_1_2?ie=UTF8&qid=1416100631&sr=8-2&keywords=25%27+extension

http://www.amazon.com/Belkin-6-Feet-Replacement-Power-Cord/dp/B00000J1UQ/ref=sr_1_2?ie=UTF8&qid=1416100695&sr=8-2&keywords=pc+cord

**Comment by mikeal** [comment]
purchased one of each of those links :)

**Comment by bcoe** [comment]
\o/ thanks a ton @mikeal. I was talking to @gabrielsilk, we'd like to show up to the storage-locker a bit early on December 13th to sort and wire-up the new equipment; I'd like to try to cut as much time as possible out of the load-in and load-out this time.

**Comment by mikeal** [comment]
sure, we can go earlier this time. are you saying you want to wire things up _in the van_? Aren't we still limited on how early we can start setting up at 25C.

**Comment by bcoe** [comment]
@mikeal I was picturing doing a little bit of organizing and prep at the storage-locker/van prior to the 4PM load-in time. Do we have access to the projector and screen on the Saturday?

**Comment by NHQ** [comment]
whoa this is all awesome.  What waterfront space precisely? 

@mikeal  i have all kinds of wants to talk to you about eventing related business / ops. 

@bcoe keep that compressor away from my algorithms tho! smh
